use super::Content;

pub static CONTENT: Content = Content {
    site_name: "Origa",

    header_features: "Features",
    header_compare: "Compare",
    header_download: "Download",
    header_integrations: "Integrations",

    footer_product: "Product",
    footer_resources: "Resources",
    footer_license: "License",

    home_meta_title: "Origa — All-in-One Japanese Learning App",
    home_meta_description: "All-in-one Japanese learning app: vocabulary, kanji, grammar, 200K+ native phrases and JLPT analytics. In your own language.",
    home_hero_title: "Learn Japanese in your own language",
    home_hero_subtitle: "Vocabulary, kanji, grammar, listening and 200,000+ native phrases — all in one app. No English required.",
    home_cta_primary: "Download",
    home_cta_secondary: "Open web app",
    home_hero_tagline: "Cross-platform · Offline-first · Privacy-first",
    home_problem_h2: "Five apps for one language",
    home_problem_text: "Vocabulary in Anki. Kanji in WaniKani. Grammar in Bunpro. Listening on YouTube. You stitch together five subscriptions and hope they somehow connect. Origa is one app — vocabulary, kanji, grammar, listening and 200,000+ phrases, built to work together from day one.",
    home_features_h2: "Everything you need. Nothing you don't.",
    home_feature_vocab_title: "Vocabulary",
    home_feature_vocab_text: "Built-in dictionaries in your language. Create cards in seconds — type a word, scan a photo, or record audio.",
    home_feature_kanji_title: "Kanji",
    home_feature_kanji_text: "Automatic furigana that hides as you learn. Writing practice with stroke order. JLPT-mapped kanji dictionaries.",
    home_feature_grammar_title: "Grammar",
    home_feature_grammar_text: "Structured grammar reference by JLPT level. Rules explained with words you already know. Practice tests.",
    home_feature_listening_title: "Phrases",
    home_feature_listening_text: "Phrases from anime, visual novels and native content with original voice acting. Auto-selected for your level.",
    home_principle_content_title: "Learn from your own content.",
    home_principle_content_text: "Study what you're actually reading, watching or listening to — not someone else's word list.",
    home_principle_fsrs_title: "Smart spaced repetition.",
    home_principle_fsrs_text: "FSRS algorithm adapts review intervals to your memory.",
    home_principle_local_title: "Everything runs locally.",
    home_principle_local_text: "All AI models and data processing happen on your device. Nothing is sent to the cloud.",
    home_principle_offline_title: "Works offline.",
    home_principle_offline_text: "Full functionality without internet. Study on the train, on a plane, anywhere.",
    home_cta_title: "Start learning Japanese your way",

    features_meta_title: "Vocabulary, Kanji, Grammar & Listening | Origa",
    features_meta_description: "Built-in dictionaries, smart flashcards, automatic furigana, JLPT grammar and 200K+ phrases with audio — all in one app.",
    features_h1: "Everything for Japanese learning",
    features_vocab_h2: "Vocabulary",
    features_vocab_label: "How it works",
    features_vocab_step1: "Type or paste a Japanese word or sentence",
    features_vocab_step2: "Scan a photo — OCR extracts words and adds translations automatically",
    features_vocab_step3: "Review with spaced repetition at optimal intervals",
    features_vocab_dict: "Built-in bilingual dictionaries",
    features_vocab_cards: "Instant card creation",
    features_vocab_audio: "NHK audio pronunciation",
    features_vocab_import: "Import from textbooks",
    features_vocab_fsrs: "FSRS spaced repetition",
    features_vocab_jlpt: "JLPT level tracking",
    features_kanji_h2: "Kanji",
    features_kanji_subtitle: "Automatic furigana, writing practice, JLPT dictionaries and interactive reading tests.",
    features_kanji_furigana: "Automatic furigana",
    features_kanji_furigana_desc: "Furigana appears above kanji and gradually hides as you master each character.",
    features_kanji_writing: "Writing practice",
    features_kanji_writing_desc: "Practice writing with correct stroke order animations.",
    features_kanji_dict: "JLPT kanji dictionaries",
    features_kanji_dict_desc: "Kanji organized by JLPT level from N5 to N1.",
    features_kanji_tests: "Interactive reading tests",
    features_kanji_tests_desc: "Test your kanji reading in context with interactive exercises.",
    features_kanji_insight: "You don't need to learn all jōyō kanji at once. Learn the ones that appear in your content.",
    features_grammar_h2: "Grammar",
    features_grammar_subtitle: "Structured grammar reference by JLPT level with contextual examples.",
    features_grammar_jlpt: "JLPT-organized reference",
    features_grammar_jlpt_desc: "Grammar points organized by JLPT level from N5 to N1.",
    features_grammar_context: "Contextual examples",
    features_grammar_context_desc: "Grammar examples use vocabulary you already know.",
    features_grammar_tests: "Practice tests",
    features_grammar_tests_desc: "Test your understanding with grammar practice tests.",
    features_grammar_search: "Grammar search",
    features_grammar_search_desc: "Look up grammar patterns directly from text you're reading.",
    features_grammar_insight: "Grammar examples use vocabulary you already know — so you focus on the pattern itself.",
    features_listening_h2: "Phrases",
    features_listening_subtitle: "Phrases from real Japanese content, auto-selected for your level.",
    features_listening_n1: "N+1 auto-selection",
    features_listening_n1_desc: "Phrases automatically selected at your current level plus one.",
    features_listening_audio: "Original voice acting",
    features_listening_audio_desc: "Audio from native Japanese content — anime, visual novels and more.",
    features_listening_comp: "Listening comprehension",
    features_listening_comp_desc: "Practice understanding spoken Japanese in context.",
    features_listening_everyday: "Everyday Japanese",
    features_listening_everyday_desc: "Learn phrases used in daily life by native speakers.",
    features_listening_insight: "These phrases come from content made by Japanese speakers, for Japanese speakers.",
    features_cta: "Start learning",

    compare_meta_title: "Origa vs Anki, WaniKani, Bunpro & Duolingo",
    compare_meta_description: "Compare Origa with Anki, WaniKani, Bunpro and Duolingo. See which Japanese learning tools work best together.",
    compare_h1: "Choosing the right Japanese learning tool",
    compare_subtitle: "There's no single perfect app. Here's an honest comparison to help you decide.",
    compare_table_feature: "Feature",
    compare_table_origa: "Origa",
    compare_table_anki: "Anki",
    compare_table_wanikani: "WaniKani",
    compare_table_bunpro: "Bunpro",
    compare_table_duolingo: "Duolingo",
    compare_vocab: "Vocabulary",
    compare_kanji: "Kanji",
    compare_grammar: "Grammar",
    compare_listening: "Listening",
    compare_languages: "Your language",
    compare_offline: "Offline",
    compare_yes: "✅",
    compare_partial: "Partial",
    compare_no: "❌",
    compare_english_only: "English only",
    compare_limited: "Limited",
    compare_manual: "Manual",
    compare_label_best_for: "Best for",
    compare_label_origa_wins: "Origa advantage",
    compare_label_together: "Using both —",
    compare_anki_title: "Anki",
    compare_anki_what: "Powerful general-purpose spaced repetition system.",
    compare_anki_when: "Multi-subject SRS or custom HTML/CSS cards.",
    compare_anki_better: "All-in-one Japanese learning in your native language, zero configuration.",
    compare_anki_together: "Import Anki decks into Origa for a unified experience.",
    compare_wanikani_title: "WaniKani",
    compare_wanikani_what: "Radical-based kanji learning platform.",
    compare_wanikani_when: "Structured kanji path from zero.",
    compare_wanikani_better: "Learn kanji you actually encounter in your content today.",
    compare_wanikani_together: "Build a foundation with WaniKani, then switch to Origa for real-world practice.",
    compare_bunpro_title: "Bunpro",
    compare_bunpro_what: "Grammar drilling platform.",
    compare_bunpro_when: "Focused grammar practice.",
    compare_bunpro_better: "Vocabulary and grammar unified — examples use words you already know.",
    compare_bunpro_together: "Use Bunpro for grammar drilling and Origa as your unified learning system.",
    compare_duolingo_title: "Duolingo",
    compare_duolingo_subtitle: "When Duolingo is right: you want a gentle introduction to Japanese.",
    compare_duolingo_start: "Gamified language learning app for beginners.",
    compare_duolingo_grow: "Real-world practice when you've outgrown beginner content.",
    compare_duolingo_together: "Start with Duolingo, then switch to Origa for growth.",
    compare_bridge_label: "Detailed comparison",
    compare_score: "Coverage",

    download_meta_title: "Download Origa — Japanese Learning App",
    download_meta_description: "Download Origa for Windows, Linux, macOS or Android. All platforms support offline mode.",
    download_h1: "Get Origa",
    download_windows: "Windows",
    download_windows_formats: ".exe, .msi",
    download_linux: "Linux",
    download_linux_formats: ".deb, .AppImage, .rpm",
    download_macos: "macOS",
    download_macos_formats: ".dmg, .app",
    download_android: "Android",
    download_android_formats: ".apk",
    download_web: "Web",
    download_ios: "iOS",
    download_ios_formats: "iPhone, iPad",
    download_ios_coming_soon: "Coming soon",
    download_button: "Download",
    download_subtitle: "Download Origa to any device — everything works offline.",
    download_try_web: "Open →",

    integrations_meta_title: "Word Sets & Integrations | Origa",
    integrations_meta_description: "Import vocabulary from Duolingo, Anki, Minna no Nihongo, Irodori, JLPT and more. Pre-built word sets ready to study.",
    integrations_h1: "Learn from what you already use",
    integrations_subtitle: "Pre-built vocabulary sets from popular Japanese learning sources. Import and start reviewing instantly.",

    integrations_tag_exam: "Exam",
    integrations_tag_app: "App",
    integrations_tag_textbook: "Textbook",
    integrations_tag_content: "Content",
    integrations_tag_import: "Import",

    integrations_jlpt_name: "JLPT",
    integrations_jlpt_desc: "Official vocabulary for the Japanese Language Proficiency Test, organized by level.",
    integrations_jlpt_detail: "N5 · N4 · N3 · N2 · N1",

    integrations_duolingo_name: "Duolingo",
    integrations_duolingo_desc: "Vocabulary extracted from Duolingo's Japanese course, available in English and Russian tracks.",
    integrations_duolingo_detail: "190+ word sets · English & Russian tracks",

    integrations_minna_name: "Minna no Nihongo",
    integrations_minna_desc: "Word lists from the most popular Japanese textbook series, organized lesson by lesson.",
    integrations_minna_detail: "みんなの日本語 · N5 · N4 · N3 · N2",

    integrations_irodori_name: "Irodori",
    integrations_irodori_desc: "Vocabulary from the Japan Foundation's free JLPT-oriented textbook series.",
    integrations_irodori_detail: "いろどり · 入門 · 初級1 · 初級2 · 54 lessons",

    integrations_migii_name: "Migii",
    integrations_migii_desc: "JLPT test preparation study sets from the Migii app, organized by level.",
    integrations_migii_detail: "JLPT prep sets by level",

    integrations_spy_name: "Spy × Family",
    integrations_spy_desc: "Vocabulary from the popular anime — learn Japanese through content you enjoy.",
    integrations_spy_detail: "Season 1 vocabulary",

    integrations_anki_name: "Anki Import",
    integrations_anki_desc: "Import any Anki deck directly into Origa. Supports .anki2, .anki21 and .anki21b formats.",
    integrations_anki_detail: ".anki2 · .anki21 · .anki21b",
    integrations_anki_note: "Import any Anki deck and continue learning where you left off — all your progress transfers.",
};
