use super::Content;

pub static CONTENT: Content = Content {
    site_name: "Origa",
    keywords: "일본어 공부, 일본어 공부 앱, 일본어 한자, 일본어 단어, 일본어 문법, 일본어 입문, 무료 일본어 공부 앱, jlpt, 일본어 회화, 일본어 공부 순서",
    breadcrumb_home: "홈",
    learning_resource_teaches_vocab: "일본어 어휘",
    learning_resource_teaches_kanji: "한자",
    learning_resource_teaches_grammar: "일본어 문법",
    learning_resource_teaches_listening: "일본어 듣기",

    header_features: "기능",
    header_compare: "비교",
    header_download: "다운로드",
    header_integrations: "콘텐츠",
    header_blog: "블로그",

    blog_index_meta_title: "Origa 블로그 — 일본어 학습 필드 노트",
    blog_index_meta_description: "일본어 학습에 대한 실전 가이드: Anki 대안, 앱 선택, 어휘, 한자, 학습 워크플로우. Origa 팀이 작성.",
    blog_index_h1: "블로그",
    blog_index_subtitle: "일본어 학습에 대한 실전 가이드 — 언제 도구를 바꿀지, 무엇을 찾을지, 각 앱이 어디서 강한지.",
    blog_index_empty: "아직 게시된 글이 없습니다. 나중에 다시 확인해 주세요.",
    blog_updated_label: "업데이트:",
    breadcrumb_blog: "블로그",

    footer_product: "제품",
    footer_resources: "리소스",
    footer_license: "라이선스",

    home_meta_title: "Origa — 일본어 공부: 한자, 문법, JLPT",
    home_meta_description: "무료 일본어 입문 및 JLPT 대비 앱: 한자, 문법, 어휘, 20만+ 원어민 문장. 완전 오프라인, 한국어 인터페이스.",
    home_schema_feature_list: "어휘, 한자, 문법, 듣기, JLPT 분석, 오프라인 모드",
    home_hero_title: "한국어로 일본어를 배우세요",
    home_hero_subtitle: "어휘, 한자, 문법, 듣기, 20만 개 이상의 원어민 문장 — 모든 것이 하나의 앱에. 영어 없이도 학습할 수 있습니다.",
    home_cta_primary: "다운로드",
    home_cta_secondary: "웹 앱 열기",
    home_hero_tagline: "크로스플랫폼 · 오프라인 · 개인정보 보호",
    home_problem_h2: "모두가 영어로 배우는 것은 아닙니다",
    home_problem_text: "대부분의 일본어 학습 도구는 영어 사용자를 위해 만들어졌습니다. 한국어를 비롯한 아시아 언어를 사용하는 사람들은 제2언어를 거쳐 번역해야 합니다. Origa는 이것을 바꿉니다. 모든 사전, 모든 문법 설명, 모든 인터페이스 요소가 첫날부터 여러분의 언어로 제공됩니다.",
    home_features_h2: "필요한 모든 것. 불필요한 것은 없습니다.",
    home_feature_vocab_title: "어휘",
    home_feature_vocab_text: "한국어 내장 사전. 단어를 입력하거나, 사진을 스캔하거나, 음성을 녹음하여 몇 초 만에 카드를 만드세요.",
    home_feature_kanji_title: "한자",
    home_feature_kanji_text: "학습 진도에 따라 숨겨지는 자동 후리가나. 올바른 획순으로 쓰기 연습. JLPT 기반 한자 사전.",
    home_feature_grammar_title: "문법",
    home_feature_grammar_text: "JLPT 레벨별 체계적인 문법 참고서. 이미 아는 단어로 설명하는 규칙. 연습 테스트.",
    home_feature_listening_title: "문장",
    home_feature_listening_text: "애니메이션, 비주얼 노벨, 원어민 콘텐츠의 문장과 원본 음성. 내 레벨에 맞게 자동 선택.",
    home_principle_content_title: "나만의 콘텐츠로 학습하세요.",
    home_principle_content_text: "다른 사람의 단어장이 아닌, 실제로 읽고, 보고, 듣는 것으로 공부하세요.",
    home_principle_fsrs_title: "스마트 간격 반복.",
    home_principle_fsrs_text: "FSRS 알고리즘이 당신의 기억에 맞게 복습 간격을 조정합니다.",
    home_principle_local_title: "모든 것이 로컬에서 실행됩니다.",
    home_principle_local_text: "모든 AI 모델과 데이터 처리는 기기에서 이루어집니다. 클라우드로 전송되지 않습니다.",
    home_principle_offline_title: "오프라인에서 작동합니다.",
    home_principle_offline_text: "인터넷 없이 모든 기능을 사용할 수 있습니다. 기차에서, 비행기에서, 어디서든 학습하세요.",
    home_cta_title: "나만의 방식으로 일본어 학습을 시작하세요",

    features_meta_title: "어휘, 한자, 문법 및 듣기 | Origa",
    features_meta_description: "내장 사전, FSRS 플래시카드, 자동 후리가나, JLPT 문법, 한자 N5–N1, 20만 개 이상의 오디오 문장. 완전 오프라인.",
    features_schema_how_to_name: "Origa로 일본어 어휘를 기르는 방법",
    features_h1: "일본어 학습에 필요한 모든 것",
    features_vocab_h2: "어휘",
    features_vocab_label: "작동 방식",
    features_vocab_step1: "일본어 단어나 문장을 입력하거나 붙여넣기",
    features_vocab_step2: "사진 스캔 — OCR이 단어를 추출하고 자동으로 번역을 추가합니다",
    features_vocab_step3: "FSRS 간격 반복으로 최적의 타이밍에 복습",
    features_vocab_dict: "내장 이중언어 사전",
    features_vocab_cards: "즉시 카드 생성",
    features_vocab_audio: "NHK 오디오 발음",
    features_vocab_import: "교재에서 가져오기",
    features_vocab_fsrs: "FSRS 간격 반복",
    features_vocab_jlpt: "JLPT 레벨 추적",
    features_kanji_h2: "한자",
    features_kanji_subtitle: "자동 후리가나, 쓰기 연습, JLPT 사전 및 인터랙티브 읽기 테스트.",
    features_kanji_furigana: "자동 후리가나",
    features_kanji_furigana_desc: "후리가나가 한자 위에 표시되며, 각 글자를 마스터할 때마다 점차 숨겨집니다.",
    features_kanji_writing: "쓰기 연습",
    features_kanji_writing_desc: "올바른 획순 애니메이션으로 쓰기 연습.",
    features_kanji_dict: "JLPT 한자 사전",
    features_kanji_dict_desc: "N5부터 N1까지 JLPT 레벨별로 정리된 한자.",
    features_kanji_tests: "인터랙티브 읽기 테스트",
    features_kanji_tests_desc: "인터랙티브 연습으로 문맥 속 한자 읽기를 테스트하세요.",
    features_kanji_insight: "모든 상용 한자를 한 번에 배울 필요는 없습니다. 여러분의 콘텐츠에 등장하는 한자를 먼저 배우세요.",
    features_grammar_h2: "문법",
    features_grammar_subtitle: "JLPT 레벨별 체계적인 문법 참고서와 문맥 예문.",
    features_grammar_jlpt: "JLPT별 참고서",
    features_grammar_jlpt_desc: "N5부터 N1까지 JLPT 레벨별로 정리된 문법 항목.",
    features_grammar_context: "문맥 예문",
    features_grammar_context_desc: "문법 예문은 이미 아는 어휘를 사용합니다.",
    features_grammar_tests: "연습 테스트",
    features_grammar_tests_desc: "문법 연습 테스트로 이해도를 확인하세요.",
    features_grammar_search: "문법 검색",
    features_grammar_search_desc: "읽고 있는 텍스트에서 직접 문법 패턴을 검색하세요.",
    features_grammar_insight: "문법 예문은 이미 아는 어휘를 사용하므로 패턴 자체에 집중할 수 있습니다.",
    features_listening_h2: "문장",
    features_listening_subtitle: "실제 일본어 콘텐츠의 문장, 내 레벨에 맞게 자동 선택.",
    features_listening_n1: "N+1 자동 선택",
    features_listening_n1_desc: "현재 레벨보다 한 단계 높은 문장이 자동으로 선택됩니다.",
    features_listening_audio: "원본 음성",
    features_listening_audio_desc: "원어민 일본어 콘텐츠의 오디오 — 애니메이션, 비주얼 노벨 등.",
    features_listening_comp: "듣기 이해",
    features_listening_comp_desc: "문맥 속 일본어 듣기 이해력을 연습하세요.",
    features_listening_everyday: "일상 일본어",
    features_listening_everyday_desc: "원어민이 일상에서 사용하는 문장을 배우세요.",
    features_listening_insight: "이 문장들은 일본인이 일본인을 위해 만든 콘텐츠에서 가져왔습니다.",
    features_cta: "학습 시작",
    features_faq_h2: "질문과 답변",
    faq_q1: "Origa로 일본어 공부는 어떻게 시작하나요?",
    faq_a1: "사용자 언어의 내장 다국어 사전으로 시작하세요. 단어, 문장, 사진, 음성에서 카드를 만들면 Origa가 후리가나를 추가하고 FSRS 알고리즘으로 복습 일정을 잡아줍니다. 처음이라면 JLPT N5부터 시작하세요.",
    faq_q2: "Origa는 Anki의 대안인가요?",
    faq_a2: "Anki는 사용자 정의 덱을 만드는 데 강력한 도구입니다. Origa는 자동 후리가나, OCR 카드 생성, 내장 사전과 함께 문법과 듣기를 하나의 앱에서 제공합니다. 기존 Anki 덱도 가져올 수 있습니다.",
    faq_q3: "오프라인으로 일본어를 공부할 수 있나요?",
    faq_a3: "네. 모든 기능이 오프라인에서 작동합니다. OCR과 음성 인식 모델이 기기에서 로컬로 실행되므로 인터넷 없이도 카드를 만들고 복습할 수 있습니다.",
    faq_q4: "Origa가 JLPT 대비에 도움이 되나요?",
    faq_a4: "네. Origa는 JLPT 레벨을 추적하고, 문법 참조를 N5부터 N1까지 정리하며, 한자 사전을 JLPT 레벨에 매핑하고, 복습 분석을 보여줍니다.",
    faq_q5: "Origa는 제 언어로도 사용할 수 있나요?",
    faq_a5: "인터페이스는 영어, 러시아어, 한국어, 베트남어로 제공되며 내장 다국어 사전이 있습니다. 시작하는 데 영어는 필요하지 않습니다.",

    compare_meta_title: "Origa vs Anki, WaniKani, Bunpro 및 Duolingo",
    compare_meta_description: "Origa를 Anki, WaniKani, Bunpro, Duolingo와 비교하세요. 어떤 일본어 학습 도구가 함께 사용하기 좋은지 확인하세요.",
    compare_h1: "올바른 일본어 학습 도구 선택하기",
    compare_subtitle: "완벽한 앱은 없습니다. 결정에 도움이 되는 정직한 비교입니다.",
    compare_table_feature: "기능",
    compare_table_origa: "Origa",
    compare_table_anki: "Anki",
    compare_table_wanikani: "WaniKani",
    compare_table_bunpro: "Bunpro",
    compare_table_duolingo: "Duolingo",
    compare_vocab: "어휘",
    compare_kanji: "한자",
    compare_grammar: "문법",
    compare_listening: "듣기",
    compare_languages: "내 언어",
    compare_offline: "오프라인",
    compare_yes: "✅",
    compare_partial: "부분 지원",
    compare_no: "❌",
    compare_english_only: "영어만",
    compare_limited: "제한적",
    compare_manual: "수동",
    compare_legend_title: "범례",
    compare_legend_origa: "Origa",
    compare_legend_supported: "지원됨",
    compare_legend_partial: "부분 지원",
    compare_legend_not_supported: "미지원",
    compare_legend_value: "특정 값",
    compare_label_best_for: "추천 대상",
    compare_label_origa_wins: "Origa의 장점",
    compare_label_together: "함께 사용하기 —",
    compare_anki_title: "Anki",
    compare_anki_what: "강력한 범용 간격 반복 시스템.",
    compare_anki_when: "다중 과목 SRS 또는 커스텀 HTML/CSS 카드.",
    compare_anki_better: "모국어로 모든 것을 갖춘 일본어 학습, 설정 불필요.",
    compare_anki_together: "Anki 덱을 Origa로 가져와 통합된 경험을 누리세요.",
    compare_wanikani_title: "WaniKani",
    compare_wanikani_what: "부수 기반 한자 학습 플랫폼.",
    compare_wanikani_when: "입문자를 위한 체계적인 한자 학습 경로.",
    compare_wanikani_better: "오늘 실제로 마주치는 한자를 배우세요.",
    compare_wanikani_together: "WaniKani로 기초를 다지고, 실전 연습은 Origa로 전환하세요.",
    compare_bunpro_title: "Bunpro",
    compare_bunpro_what: "문법 드릴 플랫폼.",
    compare_bunpro_when: "집중적인 문법 연습.",
    compare_bunpro_better: "어휘와 문법 통합 — 예문은 이미 아는 단어를 사용합니다.",
    compare_bunpro_together: "Bunpro로 문법 드릴을, Origa를 통합 학습 시스템으로 사용하세요.",
    compare_duolingo_title: "Duolingo",
    compare_duolingo_subtitle: "Duolingo가 적합한 경우: 일본어에 대한 부드러운 입문을 원할 때.",
    compare_duolingo_start: "초보자를 위한 게임화 언어 학습 앱.",
    compare_duolingo_grow: "초보자 콘텐츠를 넘어 성장하기 위한 실전 연습.",
    compare_duolingo_together: "Duolingo로 시작하고, 성장을 위해 Origa로 전환하세요.",
    compare_bridge_label: "상세 비교",
    compare_score: "커버리지",

    download_meta_title: "Origa 다운로드 — 오프라인 일본어 학습 앱",
    download_meta_description: "Windows, Linux, macOS, Android용 Origa를 무료로 다운로드하세요. 모든 플랫폼 오프라인 지원.",
    download_h1: "Origa 받기",
    download_windows: "Windows",
    download_windows_formats: ".exe, .msi",
    download_linux: "Linux",
    download_linux_formats: ".deb, .AppImage, .rpm",
    download_macos: "macOS",
    download_macos_formats: ".dmg, .app",
    download_android: "Android",
    download_android_formats: ".apk",
    download_web: "웹",
    download_ios: "iOS",
    download_ios_formats: "iPhone, iPad",
    download_ios_coming_soon: "출시 예정",
    download_button: "다운로드",
    download_subtitle: "어떤 기기에나 Origa를 다운로드하세요 — 모든 것이 오프라인에서 작동합니다.",
    download_try_web: "열기 →",

    integrations_meta_title: "단어 세트 및 콘텐츠 | Origa",
    integrations_meta_description: "Duolingo, Anki, 미나노니혼고, 이로도리, JLPT 등에서 어휘를 가져오세요. 학습 준비가 된 사전 단어 세트.",
    integrations_h1: "이미 사용하는 것으로 학습하세요",
    integrations_subtitle: "인기 있는 일본어 학습 소스의 사전 구축 단어 세트. 가져와서 즉시 복습을 시작하세요.",
    integrations_hero_stat: "7개 소스 · 1000개 이상의 단어 세트",

    integrations_section_exams: "시험 준비",
    integrations_section_textbooks: "교재",
    integrations_section_apps: "앱 및 콘텐츠",

    integrations_tag_exam: "시험",
    integrations_tag_app: "앱",
    integrations_tag_textbook: "교재",
    integrations_tag_content: "콘텐츠",
    integrations_tag_import: "가져오기",

    integrations_jlpt_name: "JLPT",
    integrations_jlpt_desc: "일본어능력시험 공식 어휘, 레벨별로 정리.",
    integrations_jlpt_detail: "N5 · N4 · N3 · N2 · N1",

    integrations_duolingo_name: "Duolingo",
    integrations_duolingo_desc: "Duolingo 일본어 코스에서 추출한 어휘. 여러 언어 트랙을 지원합니다.",
    integrations_duolingo_detail: "190개 이상의 단어 세트 · 다국어 트랙 지원",

    integrations_minna_name: "みんなの日本語",
    integrations_minna_desc: "가장 인기 있는 일본어 교재 시리즈의 단어 목록, 레슨별로 정리.",
    integrations_minna_detail: "みんなの日本語 · N5 · N4 · N3 · N2",

    integrations_irodori_name: "이로도리",
    integrations_irodori_desc: "일본국제교류기금의 무료 JLPT 지향 교재 시리즈 어휘.",
    integrations_irodori_detail: "いろどり · 入門 · 初級1 · 初級2 · 54 레슨",

    integrations_migii_name: "Migii",
    integrations_migii_desc: "Migii 앱의 JLPT 시험 준비 학습 세트, 레벨별로 정리.",
    integrations_migii_detail: "레벨별 JLPT 준비 세트",

    integrations_spy_name: "스파이 패밀리",
    integrations_spy_desc: "인기 애니메이션의 어휘 — 좋아하는 콘텐츠로 일본어를 배우세요.",
    integrations_spy_detail: "시즌 1 어휘",

    integrations_anki_name: "Anki 가져오기",
    integrations_anki_desc: "Anki 덱을 Origa로 직접 가져오세요. .anki2, .anki21 및 .anki21b 형식을 지원합니다.",
    integrations_anki_detail: ".anki2 · .anki21 · .anki21b",
    integrations_anki_note: "Anki 덱을 가져와서 중단한 곳에서 계속 학습하세요 — 모든 진행 상황이 이전됩니다.",

    banner_wip: "한국어 지원은 현재 개발 중입니다.",

    // Legal pages: English fallback. Korean legal translation requires native
    // review and is tracked separately; the WIP banner above already signals
    // the development status of this locale.
    footer_legal: "Legal",
    legal_privacy_link: "Privacy Policy",
    legal_terms_link: "Terms of Service",

    privacy_meta_title: "Privacy Policy | Origa",
    privacy_meta_description: "What data Origa collects (account, learning progress, settings), why it is collected, where it is stored, and your rights.",
    privacy_h1: "Privacy Policy",
    privacy_last_updated_label: "Last updated",
    privacy_body: super::en::PR_BODY_EN,

    terms_meta_title: "Terms of Service | Origa",
    terms_meta_description: "Terms governing use of Origa, the free Japanese-learning application distributed under the BSL license.",
    terms_h1: "Terms of Service",
    terms_last_updated_label: "Last updated",
    terms_body: super::en::TO_BODY_EN,
};
