use super::Content;

pub static CONTENT: Content = Content {
    site_name: "Origa",

    header_features: "Функции",
    header_compare: "Сравнение",
    header_download: "Скачать",
    header_integrations: "Интеграции",

    footer_product: "Продукт",
    footer_resources: "Ресурсы",
    footer_license: "Лицензия",

    home_meta_title: "Origa — Японский язык без посредников",
    home_meta_description: "Всё в одном приложении: лексика, кандзи, грамматика, 200 000+ фраз с озвучкой и аналитика JLPT. На вашем языке.",
    home_hero_title: "Японский язык на вашем родном языке",
    home_hero_subtitle: "Лексика, кандзи, грамматика, аудирование и более 200 000 фраз с оригинальной озвучкой — в одном приложении. Без английского посредника.",
    home_cta_primary: "Скачать",
    home_cta_secondary: "Открыть в браузере",
    home_hero_tagline: "Кроссплатформенный · Офлайн · Приватный",
    home_problem_h2: "Не все учат через английский",
    home_problem_text: "Большинство инструментов для изучения японского созданы для англоговорящих. Тем, кто говорит на русском, вьетнамском, корейском или индонезийском, приходится переводить через второй язык. Origa меняет это. Каждый словарь, каждое объяснение грамматики, каждый элемент интерфейса — на вашем языке с первого дня.",
    home_features_h2: "Всё, что нужно. Ничего лишнего.",
    home_feature_vocab_title: "Лексика",
    home_feature_vocab_text: "Встроенные словари на вашем языке. Создавайте карточки за секунды — введите слово, отсканируйте фото или запишите аудио.",
    home_feature_kanji_title: "Кандзи",
    home_feature_kanji_text: "Автоматическая фуригана, которая скрывается по мере изучения. Практика написания с правильным порядком черт.",
    home_feature_grammar_title: "Грамматика",
    home_feature_grammar_text: "Структурированный справочник грамматики по уровням JLPT. Правила объясняются на словах, которые вы уже знаете.",
    home_feature_listening_title: "Фразы",
    home_feature_listening_text: "Фразы из аниме, визуальных новелл и нативного контента с оригинальной озвучкой. Автоподбор по вашему уровню.",
    home_principle_content_title: "Учитесь по своему контенту.",
    home_principle_content_text: "Изучайте то, что вы реально читаете, смотрите или слушаете — а не чужие списки слов.",
    home_principle_fsrs_title: "Умное интервальное повторение.",
    home_principle_fsrs_text: "Алгоритм FSRS адаптирует интервалы повторения к вашей памяти.",
    home_principle_local_title: "Всё работает локально.",
    home_principle_local_text: "Все ИИ-модели и обработка данных происходят на вашем устройстве. Ничего не отправляется в облако.",
    home_principle_offline_title: "Работает офлайн.",
    home_principle_offline_text: "Полный функционал без интернета. Учитесь в поезде, в самолёте — где угодно.",
    home_cta_title: "Начните изучать японский по-своему",

    features_meta_title: "Лексика, кандзи, грамматика и аудирование | Origa",
    features_meta_description: "Встроенные словари, умные карточки, автоматическая фуригана, грамматика JLPT и 200 000+ фраз с аудио.",
    features_h1: "Всё для изучения японского",
    features_vocab_h2: "Лексика",
    features_vocab_label: "Как это работает",
    features_vocab_step1: "Введите или вставьте японское слово или предложение",
    features_vocab_step2: "Отсканируйте фото — OCR автоматически извлечёт слова и дополнит их переводом",
    features_vocab_step3: "Повторяйте с интервальным повторением в оптимальные интервалы",
    features_vocab_dict: "Встроенные двуязычные словари",
    features_vocab_cards: "Мгновенное создание карточек",
    features_vocab_audio: "Аудио произношение NHK",
    features_vocab_import: "Импорт из учебников",
    features_vocab_fsrs: "Интервальное повторение FSRS",
    features_vocab_jlpt: "Отслеживание уровня JLPT",
    features_kanji_h2: "Кандзи",
    features_kanji_subtitle: "Автоматическая фуригана, практика написания, словари JLPT и интерактивные тесты чтения.",
    features_kanji_furigana: "Автоматическая фуригана",
    features_kanji_furigana_desc: "Фуригана появляется над кандзи и постепенно скрывается по мере освоения каждого иероглифа.",
    features_kanji_writing: "Практика написания",
    features_kanji_writing_desc: "Практика написания с анимацией правильного порядка черт.",
    features_kanji_dict: "Словари кандзи JLPT",
    features_kanji_dict_desc: "Кандзи организованы по уровням JLPT от N5 до N1.",
    features_kanji_tests: "Интерактивные тесты чтения",
    features_kanji_tests_desc: "Проверяйте чтение кандзи в контексте с интерактивными упражнениями.",
    features_kanji_insight: "Вам не нужно учить все дзёё кандзи сразу. Учите те, которые встречаются в вашем контенте.",
    features_grammar_h2: "Грамматика",
    features_grammar_subtitle: "Структурированный справочник грамматики по уровням JLPT с контекстными примерами.",
    features_grammar_jlpt: "Справочник по уровням JLPT",
    features_grammar_jlpt_desc: "Грамматические темы организованы по уровням JLPT от N5 до N1.",
    features_grammar_context: "Контекстные примеры",
    features_grammar_context_desc: "Примеры грамматики используют лексику, которую вы уже знаете.",
    features_grammar_tests: "Практические тесты",
    features_grammar_tests_desc: "Проверьте понимание с помощью практических тестов по грамматике.",
    features_grammar_search: "Поиск грамматик",
    features_grammar_search_desc: "Ищите грамматические конструкции прямо в тексте, который вы читаете.",
    features_grammar_insight: "Примеры грамматики используют лексику, которую вы уже знаете — так вы фокусируетесь на самом паттерне.",
    features_listening_h2: "Фразы",
    features_listening_subtitle: "Фразы из реального японского контента, автоматически подобранные по вашему уровню.",
    features_listening_n1: "Автоподбор N+1",
    features_listening_n1_desc: "Фразы автоматически подбираются на вашем текущем уровне плюс один.",
    features_listening_audio: "Оригинальная озвучка",
    features_listening_audio_desc: "Аудио из нативного японского контента — аниме, визуальные новеллы и другое.",
    features_listening_comp: "Аудирование",
    features_listening_comp_desc: "Практика понимания разговорного японского в контексте.",
    features_listening_everyday: "Повседневный японский",
    features_listening_everyday_desc: "Учитесь фразам, которые носители языка используют в повседневной жизни.",
    features_listening_insight: "Эти фразы из контента, созданного японцами для японцев.",
    features_cta: "Начать изучение",

    compare_meta_title: "Origa vs Anki, WaniKani, Bunpro и Duolingo",
    compare_meta_description: "Сравните Origa с Anki, WaniKani, Bunpro и Duolingo. Узнайте, какие инструменты лучше работают вместе.",
    compare_h1: "Выбор инструмента для изучения японского",
    compare_subtitle: "Нет идеального приложения. Вот честное сравнение, которое поможет вам решить.",
    compare_table_feature: "Функция",
    compare_table_origa: "Origa",
    compare_table_anki: "Anki",
    compare_table_wanikani: "WaniKani",
    compare_table_bunpro: "Bunpro",
    compare_table_duolingo: "Duolingo",
    compare_vocab: "Лексика",
    compare_kanji: "Кандзи",
    compare_grammar: "Грамматика",
    compare_listening: "Аудирование",
    compare_languages: "Ваш язык",
    compare_offline: "Офлайн",
    compare_yes: "✅",
    compare_partial: "Частично",
    compare_no: "❌",
    compare_english_only: "Только английский",
    compare_limited: "Ограничено",
    compare_manual: "Вручную",
    compare_label_best_for: "Лучше для",
    compare_label_origa_wins: "Преимущество Origa",
    compare_label_together: "Использование обоих —",
    compare_anki_title: "Anki",
    compare_anki_what: "Мощная универсальная система интервального повторения.",
    compare_anki_when: "SRS для нескольких предметов или карточки с HTML/CSS.",
    compare_anki_better: "Комплексное изучение японского на родном языке без настройки.",
    compare_anki_together: "Импортируйте колоды Anki в Origa для единого опыта.",
    compare_wanikani_title: "WaniKani",
    compare_wanikani_what: "Платформа для изучения кандзи через радикалы.",
    compare_wanikani_when: "Структурированный путь изучения кандзи с нуля.",
    compare_wanikani_better: "Учитесь кандзи, которые реально встречаются в вашем контенте.",
    compare_wanikani_together: "Постройте базу с WaniKani, затем переходите на Origa для практики.",
    compare_bunpro_title: "Bunpro",
    compare_bunpro_what: "Платформа для тренировки грамматики.",
    compare_bunpro_when: "Целенаправленная практика грамматики.",
    compare_bunpro_better: "Лексика и грамматика вместе — примеры используют слова, которые вы уже знаете.",
    compare_bunpro_together: "Используйте Bunpro для тренировки грамматики и Origa как единую систему.",
    compare_duolingo_title: "Duolingo",
    compare_duolingo_subtitle: "Когда Duolingo подходит: вам нужно мягкое введение в японский.",
    compare_duolingo_start: "Геймифицированное приложение для начинающих.",
    compare_duolingo_grow: "Реальная практика, когда вы переросли начальный контент.",
    compare_duolingo_together: "Начните с Duolingo, затем переходите на Origa.",
    compare_bridge_label: "Подробное сравнение",
    compare_score: "Покрытие",

    download_meta_title: "Скачать Origa — приложение для японского",
    download_meta_description: "Скачайте Origa для Windows, Linux, macOS или Android. Все платформы поддерживают офлайн-режим.",
    download_h1: "Получите Origa",
    download_windows: "Windows",
    download_windows_formats: ".exe, .msi",
    download_linux: "Linux",
    download_linux_formats: ".deb, .AppImage, .rpm",
    download_macos: "macOS",
    download_macos_formats: ".dmg, .app",
    download_android: "Android",
    download_android_formats: ".apk",
    download_web: "Web",
    download_ios: "iOS",
    download_ios_formats: "iPhone, iPad",
    download_ios_coming_soon: "В разработке",
    download_button: "Скачать",
    download_subtitle: "Скачайте Origa на любое устройство — всё работает офлайн.",
    download_try_web: "Открыть →",

    integrations_meta_title: "Наборы слов и интеграции | Origa",
    integrations_meta_description: "Импортируйте лексику из Duolingo, Anki, Minna no Nihongo, Irodori, JLPT и других. Готовые наборы слов для изучения.",
    integrations_h1: "Учитесь по своим источникам",
    integrations_subtitle: "Готовые наборы слов из популярных источников для изучения японского. Импортируйте и начните повторять сразу.",

    integrations_tag_exam: "Экзамен",
    integrations_tag_app: "Приложение",
    integrations_tag_textbook: "Учебник",
    integrations_tag_content: "Контент",
    integrations_tag_import: "Импорт",

    integrations_jlpt_name: "JLPT",
    integrations_jlpt_desc: "Официальная лексика для Японского языкового теста (JLPT), организованная по уровням.",
    integrations_jlpt_detail: "N5 · N4 · N3 · N2 · N1",

    integrations_duolingo_name: "Duolingo",
    integrations_duolingo_desc: "Лексика из курса японского Duolingo, доступная на английском и русском языках.",
    integrations_duolingo_detail: "190+ наборов · Английский и русский треки",

    integrations_minna_name: "Minna no Nihongo",
    integrations_minna_desc: "Списки слов из самого популярного учебника японского, организованные по урокам.",
    integrations_minna_detail: "みんなの日本語 · N5 · N4 · N3 · N2",

    integrations_irodori_name: "Irodori",
    integrations_irodori_desc: "Лексика из бесплатной серии учебников JLPT от Японского фонда.",
    integrations_irodori_detail: "いろどり · 入門 · 初級1 · 初級2 · 54 урока",

    integrations_migii_name: "Migii",
    integrations_migii_desc: "Учебные наборы для подготовки к JLPT из приложения Migii, организованные по уровням.",
    integrations_migii_detail: "Наборы для подготовки к JLPT по уровням",

    integrations_spy_name: "Spy × Family",
    integrations_spy_desc: "Лексика из популярного аниме — учите японский через контент, который вам нравится.",
    integrations_spy_detail: "Лексика 1 сезона",

    integrations_anki_name: "Импорт Anki",
    integrations_anki_desc: "Импортируйте любую колоду Anki прямо в Origa. Поддерживаются форматы .anki2, .anki21 и .anki21b.",
    integrations_anki_detail: ".anki2 · .anki21 · .anki21b",
    integrations_anki_note: "Импортируйте любую колоду Anki и продолжайте учить с того места, где остановились — весь прогресс переносится.",
};
