use super::Content;

pub static CONTENT: Content = Content {
    site_name: "Origa",
    keywords: "học tiếng nhật, app học tiếng nhật, hán tự, từ vựng tiếng nhật, ngữ pháp tiếng nhật, học tiếng nhật miễn phí, học kanji, jlpt tiếng nhật, học tiếng nhật offline, học tiếng nhật cho người mới bắt đầu",

    header_features: "Tính năng",
    header_compare: "So sánh",
    header_download: "Tải xuống",
    header_integrations: "Nội dung",

    footer_product: "Sản phẩm",
    footer_resources: "Tài nguyên",
    footer_license: "Giấy phép",

    home_meta_title: "Origa — Học tiếng Nhật: Hán tự, Ngữ pháp, JLPT",
    home_meta_description: "Ứng dụng học tiếng Nhật miễn phí cho người mới bắt đầu: hán tự, ngữ pháp, từ vựng, 200K+ câu bản ngữ, JLPT. Offline, bằng tiếng Việt.",
    home_schema_feature_list: "Từ vựng, Hán tự, Ngữ pháp, Nghe, Phân tích JLPT, Chế độ ngoại tuyến",
    home_hero_title: "Học tiếng Nhật bằng tiếng Việt",
    home_hero_subtitle: "Từ vựng, hán tự, ngữ pháp, nghe và hơn 200.000 câu bản ngữ — tất cả trong một ứng dụng. Không cần tiếng Anh.",
    home_cta_primary: "Tải xuống",
    home_cta_secondary: "Mở ứng dụng web",
    home_hero_tagline: "Đa nền tảng · Ngoại tuyến · Bảo mật",
    home_problem_h2: "Không phải ai cũng học qua tiếng Anh",
    home_problem_text: "Hầu hết công cụ học tiếng Nhật đều được tạo cho người nói tiếng Anh. Những người nói tiếng Việt phải dịch qua ngôn ngữ thứ hai. Origa thay đổi điều đó. Mọi từ điển, mọi giải thích ngữ pháp, mọi thành phần giao diện đều bằng ngôn ngữ của bạn ngay từ ngày đầu tiên.",
    home_features_h2: "Tất cả những gì bạn cần. Không có gì thừa.",
    home_feature_vocab_title: "Từ vựng",
    home_feature_vocab_text: "Từ điển tích hợp bằng tiếng Việt. Tạo thẻ trong vài giây — gõ từ, quét ảnh hoặc ghi âm.",
    home_feature_kanji_title: "Hán tự",
    home_feature_kanji_text: "Furigana tự động ẩn dần khi bạn học. Luyện viết với thứ tự nét đúng. Từ điển hán tự theo JLPT.",
    home_feature_grammar_title: "Ngữ pháp",
    home_feature_grammar_text: "Tài liệu ngữ pháp có cấu trúc theo cấp độ JLPT. Quy tắc được giải thích bằng từ bạn đã biết. Bài kiểm tra thực hành.",
    home_feature_listening_title: "Câu",
    home_feature_listening_text: "Câu từ anime, visual novel và nội dung bản ngữ với lồng tiếng gốc. Tự động chọn theo cấp độ của bạn.",
    home_principle_content_title: "Học từ nội dung của riêng bạn.",
    home_principle_content_text: "Học những gì bạn thực sự đang đọc, xem hoặc nghe — chứ không phải danh sách từ của người khác.",
    home_principle_fsrs_title: "Lặp lại ngắt quãng thông minh.",
    home_principle_fsrs_text: "Thuật toán FSRS điều chỉnh khoảng thời gian ôn tập theo trí nhớ của bạn.",
    home_principle_local_title: "Mọi thứ chạy cục bộ.",
    home_principle_local_text: "Tất cả mô hình AI và xử lý dữ liệu diễn ra trên thiết bị của bạn. Không có gì được gửi lên đám mây.",
    home_principle_offline_title: "Hoạt động ngoại tuyến.",
    home_principle_offline_text: "Đầy đủ chức năng không cần internet. Học trên tàu, trên máy bay, bất cứ đâu.",
    home_cta_title: "Bắt đầu học tiếng Nhật theo cách của bạn",

    features_meta_title: "Hán tự, Ngữ pháp, Từ vựng & Nghe | Origa",
    features_meta_description: "Từ điển tích hợp, flashcard FSRS, furigana tự động, ngữ pháp JLPT, hán tự N5–N1 và hơn 200.000 câu có audio — tất cả trong một ứng dụng.",
    features_schema_how_to_name: "Cách xây dựng từ vựng tiếng Nhật với Origa",
    features_h1: "Tất cả để học tiếng Nhật",
    features_vocab_h2: "Từ vựng",
    features_vocab_label: "Cách hoạt động",
    features_vocab_step1: "Gõ hoặc dán từ hoặc câu tiếng Nhật",
    features_vocab_step2: "Quét ảnh — OCR trích xuất từ và tự động thêm bản dịch",
    features_vocab_step3: "Ôn tập với lặp lại ngắt quãng ở khoảng thời gian tối ưu",
    features_vocab_dict: "Từ điển song ngữ tích hợp",
    features_vocab_cards: "Tạo thẻ tức thì",
    features_vocab_audio: "Phát âm âm thanh NHK",
    features_vocab_import: "Nhập từ giáo trình",
    features_vocab_fsrs: "Lặp lại ngắt quãng FSRS",
    features_vocab_jlpt: "Theo dõi cấp độ JLPT",
    features_kanji_h2: "Hán tự",
    features_kanji_subtitle: "Furigana tự động, luyện viết, từ điển JLPT và bài kiểm tra đọc tương tác.",
    features_kanji_furigana: "Furigana tự động",
    features_kanji_furigana_desc: "Furigana xuất hiện phía trên hán tự và dần ẩn đi khi bạn thành thạo từng chữ.",
    features_kanji_writing: "Luyện viết",
    features_kanji_writing_desc: "Luyện viết với hoạt ảnh thứ tự nét đúng.",
    features_kanji_dict: "Từ điển hán tự JLPT",
    features_kanji_dict_desc: "Hán tự được tổ chức theo cấp độ JLPT từ N5 đến N1.",
    features_kanji_tests: "Bài kiểm tra đọc tương tác",
    features_kanji_tests_desc: "Kiểm tra cách đọc hán tự trong ngữ cảnh với bài tập tương tác.",
    features_kanji_insight: "Bạn không cần học tất cả hán tự thường dùng cùng lúc. Học những hán tự xuất hiện trong nội dung của bạn trước.",
    features_grammar_h2: "Ngữ pháp",
    features_grammar_subtitle: "Tài liệu ngữ pháp có cấu trúc theo cấp độ JLPT với ví dụ theo ngữ cảnh.",
    features_grammar_jlpt: "Tài liệu theo cấp độ JLPT",
    features_grammar_jlpt_desc: "Điểm ngữ pháp được tổ chức theo cấp độ JLPT từ N5 đến N1.",
    features_grammar_context: "Ví dụ theo ngữ cảnh",
    features_grammar_context_desc: "Ví dụ ngữ pháp sử dụng từ vựng bạn đã biết.",
    features_grammar_tests: "Bài kiểm tra thực hành",
    features_grammar_tests_desc: "Kiểm tra hiểu biết của bạn với bài kiểm tra thực hành ngữ pháp.",
    features_grammar_search: "Tìm kiếm ngữ pháp",
    features_grammar_search_desc: "Tìm mẫu ngữ pháp trực tiếp từ văn bản bạn đang đọc.",
    features_grammar_insight: "Ví dụ ngữ pháp sử dụng từ vựng bạn đã biết — để bạn tập trung vào mẫu chính.",
    features_listening_h2: "Câu",
    features_listening_subtitle: "Câu từ nội dung tiếng Nhật thực tế, tự động chọn theo cấp độ của bạn.",
    features_listening_n1: "Tự động chọn N+1",
    features_listening_n1_desc: "Câu được tự động chọn ở cấp độ cao hơn mức hiện tại của bạn một bậc.",
    features_listening_audio: "Lồng tiếng gốc",
    features_listening_audio_desc: "Âm thanh từ nội dung tiếng Nhật bản ngữ — anime, visual novel và hơn thế.",
    features_listening_comp: "Khả năng nghe hiểu",
    features_listening_comp_desc: "Thực hành hiểu tiếng Nhật nói trong ngữ cảnh.",
    features_listening_everyday: "Tiếng Nhật hàng ngày",
    features_listening_everyday_desc: "Học câu được người bản ngữ sử dụng trong cuộc sống hàng ngày.",
    features_listening_insight: "Những câu này đến từ nội dung do người Nhật tạo ra cho người Nhật.",
    features_cta: "Bắt đầu học",

    compare_meta_title: "Origa vs Anki, WaniKani, Bunpro và Duolingo",
    compare_meta_description: "So sánh Origa với Anki, WaniKani, Bunpro và Duolingo. Xem công cụ học tiếng Nhật nào hoạt động tốt nhất cùng nhau.",
    compare_h1: "Chọn công cụ học tiếng Nhật phù hợp",
    compare_subtitle: "Không có ứng dụng hoàn hảo duy nhất. Đây là so sánh trung thực để giúp bạn quyết định.",
    compare_table_feature: "Tính năng",
    compare_table_origa: "Origa",
    compare_table_anki: "Anki",
    compare_table_wanikani: "WaniKani",
    compare_table_bunpro: "Bunpro",
    compare_table_duolingo: "Duolingo",
    compare_vocab: "Từ vựng",
    compare_kanji: "Hán tự",
    compare_grammar: "Ngữ pháp",
    compare_listening: "Nghe",
    compare_languages: "Ngôn ngữ của bạn",
    compare_offline: "Ngoại tuyến",
    compare_yes: "✅",
    compare_partial: "Một phần",
    compare_no: "❌",
    compare_english_only: "Chỉ tiếng Anh",
    compare_limited: "Hạn chế",
    compare_manual: "Thủ công",
    compare_legend_title: "Chú giải",
    compare_legend_origa: "Origa",
    compare_legend_supported: "Được hỗ trợ",
    compare_legend_partial: "Một phần",
    compare_legend_not_supported: "Không hỗ trợ",
    compare_legend_value: "Giá trị cụ thể",
    compare_label_best_for: "Phù hợp nhất cho",
    compare_label_origa_wins: "Ưu điểm của Origa",
    compare_label_together: "Sử dụng cả hai —",
    compare_anki_title: "Anki",
    compare_anki_what: "Hệ thống lặp lại ngắt quãng đa năng mạnh mẽ.",
    compare_anki_when: "SRS đa môn hoặc thẻ HTML/CSS tùy chỉnh.",
    compare_anki_better: "Học tiếng Nhật toàn diện bằng tiếng mẹ đẻ, không cần cấu hình.",
    compare_anki_together: "Nhập bộ bài Anki vào Origa để có trải nghiệm thống nhất.",
    compare_wanikani_title: "WaniKani",
    compare_wanikani_what: "Nền tảng học hán tự dựa trên bộ thủ.",
    compare_wanikani_when: "Lộ trình học hán tự có cấu trúc từ con số không.",
    compare_wanikani_better: "Học hán tự bạn thực sự gặp trong nội dung của mình ngay hôm nay.",
    compare_wanikani_together: "Xây dựng nền tảng với WaniKani, sau đó chuyển sang Origa để thực hành thực tế.",
    compare_bunpro_title: "Bunpro",
    compare_bunpro_what: "Nền tảng luyện tập ngữ pháp.",
    compare_bunpro_when: "Thực hành ngữ pháp tập trung.",
    compare_bunpro_better: "Từ vựng và ngữ pháp thống nhất — ví dụ sử dụng từ bạn đã biết.",
    compare_bunpro_together: "Dùng Bunpro để luyện ngữ pháp và Origa làm hệ thống học tập thống nhất.",
    compare_duolingo_title: "Duolingo",
    compare_duolingo_subtitle: "Khi Duolingo phù hợp: bạn muốn làm quen nhẹ nhàng với tiếng Nhật.",
    compare_duolingo_start: "Ứng dụng học ngôn ngữ dạng trò chơi cho người mới bắt đầu.",
    compare_duolingo_grow: "Thực hành thực tế khi bạn đã vượt qua nội dung người mới bắt đầu.",
    compare_duolingo_together: "Bắt đầu với Duolingo, sau đó chuyển sang Origa để phát triển.",
    compare_bridge_label: "So sánh chi tiết",
    compare_score: "Độ phủ",

    download_meta_title: "Tải Origa — ứng dụng học tiếng Nhật offline",
    download_meta_description: "Tải Origa miễn phí cho Windows, Linux, macOS hoặc Android. Học tiếng Nhật offline.",
    download_h1: "Tải Origa",
    download_windows: "Windows",
    download_windows_formats: ".exe, .msi",
    download_linux: "Linux",
    download_linux_formats: ".deb, .AppImage, .rpm",
    download_macos: "macOS",
    download_macos_formats: ".dmg, .app",
    download_android: "Android",
    download_android_formats: ".apk",
    download_web: "Web",
    download_ios: "iOS",
    download_ios_formats: "iPhone, iPad",
    download_ios_coming_soon: "Sắp ra mắt",
    download_button: "Tải xuống",
    download_subtitle: "Tải Origa xuống mọi thiết bị — học tiếng Nhật ngoại tuyến.",
    download_try_web: "Mở →",

    integrations_meta_title: "Bộ từ vựng & Nội dung | Origa",
    integrations_meta_description: "Nhập từ vựng từ Duolingo, Anki, Minna no Nihongo, Irodori, JLPT và nhiều hơn nữa. Bộ từ sẵn sàng để học tiếng Nhật.",
    integrations_h1: "Học từ những nguồn bạn đã sử dụng",
    integrations_subtitle: "Bộ từ vựng được xây dựng sẵn từ các nguồn học tiếng Nhật phổ biến. Nhập và bắt đầu ôn tập ngay lập tức.",
    integrations_hero_stat: "7 nguồn · hơn 1000 bộ từ",

    integrations_section_exams: "Chuẩn bị thi",
    integrations_section_textbooks: "Giáo trình",
    integrations_section_apps: "Ứng dụng & Nội dung",

    integrations_tag_exam: "Kỳ thi",
    integrations_tag_app: "Ứng dụng",
    integrations_tag_textbook: "Giáo trình",
    integrations_tag_content: "Nội dung",
    integrations_tag_import: "Nhập",

    integrations_jlpt_name: "JLPT",
    integrations_jlpt_desc: "Từ vựng chính thức cho Kỳ thi Năng lực Tiếng Nhật, được tổ chức theo cấp độ.",
    integrations_jlpt_detail: "N5 · N4 · N3 · N2 · N1",

    integrations_duolingo_name: "Duolingo",
    integrations_duolingo_desc: "Từ vựng trích xuất từ khóa học tiếng Nhật Duolingo. Hỗ trợ nhiều ngôn ngữ.",
    integrations_duolingo_detail: "Hơn 190 bộ từ · Hỗ trợ nhiều ngôn ngữ",

    integrations_minna_name: "Minna no Nihongo",
    integrations_minna_desc: "Danh sách từ từ bộ giáo trình tiếng Nhật phổ biến nhất, tổ chức theo bài học.",
    integrations_minna_detail: "みんなの日本語 · N5 · N4 · N3 · N2",

    integrations_irodori_name: "Irodori",
    integrations_irodori_desc: "Từ vựng từ bộ giáo trình hướng tới JLPT miễn phí của Quỹ Giao lưu Quốc tế Nhật Bản.",
    integrations_irodori_detail: "いろどり · 入門 · 初級1 · 初級2 · 54 bài học",

    integrations_migii_name: "Migii",
    integrations_migii_desc: "Bộ học chuẩn bị thi JLPT từ ứng dụng Migii, tổ chức theo cấp độ.",
    integrations_migii_detail: "Bộ chuẩn bị JLPT theo cấp độ",

    integrations_spy_name: "Spy × Family",
    integrations_spy_desc: "Từ vựng từ anime nổi tiếng — học tiếng Nhật qua nội dung bạn yêu thích.",
    integrations_spy_detail: "Từ vựng mùa 1",

    integrations_anki_name: "Nhập từ Anki",
    integrations_anki_desc: "Nhập bất kỳ bộ bài Anki nào trực tiếp vào Origa. Hỗ trợ định dạng .anki2, .anki21 và .anki21b.",
    integrations_anki_detail: ".anki2 · .anki21 · .anki21b",
    integrations_anki_note: "Nhập bộ bài Anki và tiếp tục học từ nơi bạn dừng lại — mọi tiến trình được chuyển sang.",

    banner_wip: "Hỗ trợ tiếng Việt đang được phát triển.",
};
