version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "yurvon-screamo"
    assignees:
      - "yurvon-screamo"
    labels:
      - "dependencies"
    rebase-strategy: "auto"
    commit-message:
      prefix: "cargo"

  - package-ecosystem: "npm"
    directory: "/end2end"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "yurvon-screamo"
    assignees:
      - "yurvon-screamo"
    labels:
      - "dependencies"
    rebase-strategy: "auto"
    commit-message:
      prefix: "npm"
    groups:
      dev-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/tauri"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "yurvon-screamo"
    assignees:
      - "yurvon-screamo"
    labels:
      - "dependencies"
    rebase-strategy: "auto"
    commit-message:
      prefix: "npm"
    groups:
      dev-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/origa_landing"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "yurvon-screamo"
    assignees:
      - "yurvon-screamo"
    labels:
      - "dependencies"
    rebase-strategy: "auto"
    commit-message:
      prefix: "npm"
    groups:
      dev-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/origa_landing"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "yurvon-screamo"
    assignees:
      - "yurvon-screamo"
    labels:
      - "dependencies"
    rebase-strategy: "auto"
    commit-message:
      prefix: "docker"

  - package-ecosystem: "docker"
    directory: "/origa_ui"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "yurvon-screamo"
    assignees:
      - "yurvon-screamo"
    labels:
      - "dependencies"
    rebase-strategy: "auto"
    commit-message:
      prefix: "docker"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "yurvon-screamo"
    assignees:
      - "yurvon-screamo"
    labels:
      - "dependencies"
    rebase-strategy: "auto"
    commit-message:
      prefix: "ci"
