"""Generate CDN manifest and deploy incrementally to S3.

Single-file orchestrator: generates a local manifest of versioned files,
compares against the remote manifest, uploads the diff, syncs content
directories, then re-publishes the manifest. Cache-Control per object comes
from ``_cdn_cache`` (tiered policy); S3 transport lives in ``_cdn_s3``;
CDN-side HTTP verification lives in ``_cdn_verify``.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import zlib
from datetime import datetime, timezone
from pathlib import Path

import _cdn_cache
import _cdn_s3
import _cdn_verify

VERSIONED_FILES: list[str] = [
    "dictionary/chunk_01.json",
    "dictionary/chunk_02.json",
    "dictionary/chunk_03.json",
    "dictionary/chunk_04.json",
    "dictionary/chunk_05.json",
    "dictionary/chunk_06.json",
    "dictionary/chunk_07.json",
    "dictionary/chunk_08.json",
    "dictionary/chunk_09.json",
    "dictionary/chunk_10.json",
    "dictionary/chunk_11.json",
    "dictionary/kanji.json",
    "dictionary/radicals.json",
    "grammar/grammar.json",
    "grammar/grammar_v2.json",
    "grammar/grammar_ko_vi.json",
    # Tokenization precompute for grammar (#521) — freshness includes the
    # tokenizer inputs, see grammar_precompute_source()
    "grammar/grammar_precompute.rkyv",
    "dictionaries/JmdictFurigana.txt",
    # Pre-parsed rkyv blobs (deterministic, regenerated by
    # `utils build-cdn-rkyv` — see regenerate_rkyv_blobs below)
    "dictionaries/JmdictFurigana.rkyv",
    "dictionary/vocabulary.rkyv",
    "phrases/phrase_index.rkyv",
    "pitch/index.rkyv",
    # SudachiDict (lindera 5.x, current clients)
    "dictionaries/sudachidict-20260723/char_def.bin",
    "dictionaries/sudachidict-20260723/matrix.mtx",
    "dictionaries/sudachidict-20260723/dict.trie",
    "dictionaries/sudachidict-20260723/dict.valsidx",
    "dictionaries/sudachidict-20260723/dict.vals",
    "dictionaries/sudachidict-20260723/unk.bin",
    "dictionaries/sudachidict-20260723/dict.wordsidx",
    "dictionaries/sudachidict-20260723/dict.words",
    "dictionaries/sudachidict-20260723/metadata.json",
    "phrases/phrase_index.json",
    "pitch/index.json",
    "well_known_set/jlpt_n5.json",
    "well_known_set/jlpt_n4.json",
    "well_known_set/jlpt_n3.json",
    "well_known_set/jlpt_n2.json",
    "well_known_set/jlpt_n1.json",
    "well_known_set/well_known_types_meta.json",
    "well_known_set/well_known_sets_meta.json",
    # Phrase data bundles (4 files, ~12 MB each, replace 198 individual chunks)
    "phrases/data_bundle_0.json",
    "phrases/data_bundle_1.json",
    "phrases/data_bundle_2.json",
    "phrases/data_bundle_3.json",
    "phrases/data_bundle_4.json",
    "phrases/data_bundle_5.json",
    # Kanji JLPT bundles (10 files: 5 animation + 5 frames)
    "kanji_animations_n5.json",
    "kanji_animations_n4.json",
    "kanji_animations_n3.json",
    "kanji_animations_n2.json",
    "kanji_animations_n1.json",
    "kanji_frames_n5.json",
    "kanji_frames_n4.json",
    "kanji_frames_n3.json",
    "kanji_frames_n2.json",
    "kanji_frames_n1.json",
]

SYNC_DIRS = [
    "kanji_animations",
    "kanji_frames",
    "ndlocr",
    "phrases/audio",
    "phrases/data",
    # Tokenization precompute blobs (#521): cache-busted by the phrase
    # index hash exactly like the data chunks they mirror.
    "phrases/precomputed",
    "whisper",
    "fonts",
    "well_known_set/duolingo",
    "well_known_set/irodori_nyuumon",
    "well_known_set/irodori_shokyuu1",
    "well_known_set/irodori_shokyuu2",
    "well_known_set/migii",
    "well_known_set/minna_n5",
    "well_known_set/minna_n4",
    "well_known_set/minna_n3",
    "well_known_set/minna_n2",
    "well_known_set/spy_family",
]

# Kanji JLPT bundles — deployed as individual files (not in SYNC_DIRS because
# they're generated top-level files in cdn/, not in a subdirectory)
KANJI_BUNDLE_FILES = [
    "kanji_animations_n5.json",
    "kanji_animations_n4.json",
    "kanji_animations_n3.json",
    "kanji_animations_n2.json",
    "kanji_animations_n1.json",
    "kanji_frames_n5.json",
    "kanji_frames_n4.json",
    "kanji_frames_n3.json",
    "kanji_frames_n2.json",
    "kanji_frames_n1.json",
]

MANIFEST_VERSION = 1
CHUNK_SIZE = 8192


def sha256_hex(path: Path) -> str:
    hasher = hashlib.sha256()
    with path.open("rb") as f:
        while chunk := f.read(CHUNK_SIZE):
            hasher.update(chunk)
    return hasher.hexdigest()


def generate_manifest(cdn_dir: Path) -> dict[str, object]:
    files: dict[str, str] = {}

    for relative_path in VERSIONED_FILES:
        full_path = cdn_dir / relative_path
        if not full_path.is_file():
            print(f"WARNING: {relative_path} not found, skipping", file=sys.stderr)
            continue
        files[relative_path] = sha256_hex(full_path)

    if not files:
        print("ERROR: no versioned files found in cdn/", file=sys.stderr)
        sys.exit(1)

    return {
        "version": MANIFEST_VERSION,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "files": dict(sorted(files.items())),
    }


def compare_manifests(
    local: dict[str, object],
    remote: dict[str, object] | None,
) -> tuple[list[str], list[str]]:
    if remote is None:
        return list(local["files"]), []

    remote_files = remote.get("files", {})
    local_files = local["files"]

    changed: list[str] = []
    unchanged: list[str] = []

    for path, hash_val in local_files.items():
        if remote_files.get(path) != hash_val:
            changed.append(path)
        else:
            unchanged.append(path)

    return changed, unchanged


def compute_files_to_upload(
    local_manifest: dict[str, object],
    remote_manifest: dict[str, object] | None,
    force: bool,
) -> tuple[list[str], list[str]]:
    """Decide which versioned files to upload.

    With ``force=True`` every local file is treated as changed, bypassing the
    manifest hash comparison. This is the recovery path for the case where the
    remote manifest is already current but the underlying S3 objects are stale
    (partial deploy, immutable-cache poisoning): manifest-only comparison would
    falsely report "no changes" in that situation and the CDN would stay
    broken.
    """
    if force:
        local_files = local_manifest["files"]
        return list(local_files), []
    return compare_manifests(local_manifest, remote_manifest)


def validate_grammar_if_changed(changed: list[str]) -> None:
    """Fail-loud gate: validate grammar_v2.json before it ships (#501).

    Runs only when the grammar corpus is part of this deploy's change set,
    so unrelated CDN deploys are never blocked by in-flight content passes.
    The `--force-all` recovery path bypasses this gate by design.
    """
    if "grammar/grammar_v2.json" not in changed:
        return
    script = Path(__file__).resolve().parent / "validate_grammar_v2.py"
    print("\nStep 3.5: Validating grammar_v2.json...")
    result = subprocess.run(
        [sys.executable, str(script)], capture_output=True, text=True
    , check=False)
    for line in result.stdout.strip().splitlines():
        print(f"  {line}")
    for line in result.stderr.strip().splitlines():
        print(f"  {line}", file=sys.stderr)
    if result.returncode != 0:
        print(
            "  grammar_v2.json FAILED validation — deploy aborted",
            file=sys.stderr,
        )
        sys.exit(1)


def upload_versioned_files(
    cdn_dir: Path,
    files: list[str],
    dry_run: bool,
) -> None:
    if not files:
        print("No changed versioned files to upload.")
        return

    print(f"\nUploading {len(files)} changed versioned file(s):")
    for relative_path in sorted(files):
        local_path = cdn_dir / relative_path
        cache_control = _cdn_cache.cache_control_for(relative_path)
        print(f"  {relative_path}  [{cache_control}]")
        _cdn_s3.upload_file(local_path, relative_path, cache_control, dry_run)


def sync_directories(cdn_dir: Path, dry_run: bool, ignore_mtime: bool = False) -> None:
    print("\nSyncing directories:")
    for dir_name in SYNC_DIRS:
        local_dir = cdn_dir / dir_name
        if not local_dir.is_dir():
            print(f"  {dir_name}/ — not found locally, skipping")
            continue

        # Each SYNC_DIR is homogeneous in update frequency (all-ML, all-art,
        # all-content), so one Cache-Control per directory is correct.
        cache_control = _cdn_cache.cache_control_for(dir_name + "/")
        print(f"  {dir_name}/  [{cache_control}]")
        _cdn_s3.sync_directory(local_dir, dir_name, cache_control, dry_run, ignore_mtime)


def upload_manifest(cdn_dir: Path, dry_run: bool) -> None:
    manifest_path = cdn_dir / "manifest.json"
    cache_control = _cdn_cache.cache_control_for("manifest.json")
    print(f"\nUploading manifest.json (Cache-Control: {cache_control})")
    _cdn_s3.upload_file(manifest_path, "manifest.json", cache_control, dry_run)


# --- Pre-parsed rkyv blobs (furigana, vocabulary) ----------------------------
#
# Blobs are built offline by `cargo run -p utils -- build-cdn-rkyv` from the
# editable sources. Clients load them instead of parsing text/JSON on every
# cold start. Each blob header embeds sha256 of its concatenated sources, so
# freshness is verifiable without re-parsing the payload: a stale (or
# missing) blob next to changed sources aborts the deploy instead of
# silently serving an outdated dictionary to every client.

RKYV_MAGIC = b"ORFG"
# Keep in sync with origa/src/dictionary/cdn_blob.rs SCHEMA_VERSION
# (v2: VocabularyInfo gained vi/ko fields when the KO/VI chunks shipped).
RKYV_SCHEMA_VERSION = 2
RKYV_HEADER_LEN = 72

RKYV_BLOB_SOURCES: dict[str, list[str]] = {
    "dictionaries/JmdictFurigana.rkyv": ["dictionaries/JmdictFurigana.txt"],
    "dictionary/vocabulary.rkyv": [
        f"dictionary/chunk_{index:02d}.json" for index in range(1, 12)
    ],
    "phrases/phrase_index.rkyv": ["phrases/phrase_index.json"],
    "pitch/index.rkyv": ["pitch/index.json"],
}

# Deflated precompute blobs (#521): stored deflate-compressed on the CDN
# (string-heavy payloads shrink to ~a quarter). Their source hash also
# includes the tokenizer inputs so a dictionary bump forces regeneration.
# Keep in sync with the OTHER copies of the dictionary version:
# SUDACHIDICT_DIR in origa, origa_ui/build.rs and VERSIONED_FILES above —
# a forgotten bump fails loud here (freshness hash mismatch), but every
# copy must move together.
SUDACHIDICT_DIR_NAME = "sudachidict-20260723"


def grammar_precompute_source(cdn_dir: Path) -> bytes | None:
    """Byte string the grammar precompute header hash binds to.

    Mirrors utils build-grammar-precompute: both grammar JSONs plus
    `|sudachidict:<dir>|furigana:<sha256(JmdictFurigana.txt)>`.
    Returns None when an input file is missing (reported as a problem).
    """
    parts: list[bytes] = []
    for name in ("grammar/grammar_v2.json", "grammar/grammar_ko_vi.json"):
        path = cdn_dir / name
        if not path.is_file():
            return None
        parts.append(path.read_bytes())
    furigana = cdn_dir / "dictionaries/JmdictFurigana.txt"
    if not furigana.is_file():
        return None
    parts.append(b"|sudachidict:" + SUDACHIDICT_DIR_NAME.encode())
    parts.append(b"|furigana:" + hashlib.sha256(furigana.read_bytes()).digest())
    return b"".join(parts)


def inflate_deflated(blob_path: Path) -> bytes:
    """Raw-deflate a stored blob back to its built form."""
    decompressor = zlib.decompressobj(wbits=-15)
    return decompressor.decompress(blob_path.read_bytes()) + decompressor.flush()


def parse_rkyv_header(blob_path: Path) -> tuple[int, bytes]:
    """Return (schema_version, source_sha256_raw) or raise ValueError."""
    data = blob_path.read_bytes()
    if len(data) < RKYV_HEADER_LEN:
        raise ValueError(f"shorter than the {RKYV_HEADER_LEN}-byte header")
    if data[:4] != RKYV_MAGIC:
        raise ValueError("magic mismatch")
    schema_version = int.from_bytes(data[4:8], "little")
    return schema_version, data[8:40]


def rkyv_blob_freshness_problems(cdn_dir: Path) -> list[str]:
    """Freshness check for every rkyv blob: existing file, current schema,
    header source hash == sha256 of the concatenated on-disk sources."""
    problems: list[str] = []
    for blob_path, source_paths in RKYV_BLOB_SOURCES.items():
        blob = cdn_dir / blob_path
        if not blob.is_file():
            problems.append(f"{blob_path}: missing (run utils build-cdn-rkyv)")
            continue
        try:
            schema_version, header_source_sha = parse_rkyv_header(blob)
        except ValueError as e:
            problems.append(f"{blob_path}: unreadable header ({e})")
            continue
        if schema_version != RKYV_SCHEMA_VERSION:
            problems.append(
                f"{blob_path}: schema {schema_version} != {RKYV_SCHEMA_VERSION}"
            )
            continue

        hasher = hashlib.sha256()
        for source_path in source_paths:
            source_file = cdn_dir / source_path
            if not source_file.is_file():
                problems.append(f"{blob_path}: source {source_path} not found")
                break
            hasher.update(source_file.read_bytes())
        else:
            if hasher.digest() != header_source_sha:
                problems.append(f"{blob_path}: stale relative to {source_paths}")
    return problems


def grammar_precompute_freshness_problems(cdn_dir: Path) -> list[str]:
    """Freshness check for the deflated grammar precompute blob."""
    blob = cdn_dir / "grammar/grammar_precompute.rkyv"
    if not blob.is_file():
        return [
            "grammar/grammar_precompute.rkyv: missing "
            "(run utils build-grammar-precompute)"
        ]
    try:
        inflated = inflate_deflated(blob)
    except zlib.error as e:
        return [f"grammar/grammar_precompute.rkyv: not deflated ({e})"]
    if len(inflated) < RKYV_HEADER_LEN or inflated[:4] != RKYV_MAGIC:
        return ["grammar/grammar_precompute.rkyv: unreadable header"]
    schema_version = int.from_bytes(inflated[4:8], "little")
    if schema_version != RKYV_SCHEMA_VERSION:
        return [
            f"grammar/grammar_precompute.rkyv: schema {schema_version} "
            f"!= {RKYV_SCHEMA_VERSION}"
        ]
    source = grammar_precompute_source(cdn_dir)
    if source is None:
        return ["grammar/grammar_precompute.rkyv: source inputs missing"]
    if hashlib.sha256(source).digest() != inflated[8:40]:
        return ["grammar/grammar_precompute.rkyv: stale relative to its sources"]
    return []


def assert_rkyv_blobs_fresh(cdn_dir: Path) -> None:
    problems = rkyv_blob_freshness_problems(cdn_dir)
    problems += grammar_precompute_freshness_problems(cdn_dir)
    if problems:
        for problem in problems:
            print(f"ERROR: rkyv blob freshness: {problem}", file=sys.stderr)
        sys.exit(1)


def regenerate_rkyv_blobs(project_root: Path) -> None:
    """Rebuild rkyv blobs whose sources changed; fail the deploy on error."""
    result = subprocess.run(
        ["cargo", "run", "-p", "utils", "--", "build-cdn-rkyv"],
        capture_output=True,
        text=True,
        cwd=str(project_root),
        check=False,
    )
    for line in result.stdout.strip().splitlines():
        print(f"  {line}")
    if result.returncode != 0:
        print(f"  build-cdn-rkyv FAILED: {result.stderr}", file=sys.stderr)
        sys.exit(1)


def regenerate_precompute_blobs(project_root: Path) -> None:
    """Rebuild the #521 tokenization precompute blobs (grammar + phrases).

    Both builders skip chunks/blobs whose header is fresh, so a routine
    deploy only pays for what actually changed. A full rebuild takes
    ~80s for the 156k phrase dataset (native lindera).
    """
    for command in ("build-grammar-precompute", "build-phrase-precompute"):
        result = subprocess.run(
            ["cargo", "run", "-p", "utils", "--", command],
            capture_output=True,
            text=True,
            cwd=str(project_root),
            check=False,
        )
        for line in result.stdout.strip().splitlines():
            print(f"  {line}")
        if result.returncode != 0:
            print(f"  {command} FAILED: {result.stderr}", file=sys.stderr)
            sys.exit(1)


def _force_all_deploy(dry_run: bool) -> None:
    """Upload everything from cdn/ to R2 via boto3 only (no aws CLI).

    Skips all remote reads (manifest download, remote object listing).
    Uploads versioned files + syncs all directories. Shows progress per dir.
    """
    import time as _time

    project_root = Path(__file__).resolve().parent.parent
    cdn_dir = project_root / "cdn"
    if not cdn_dir.is_dir():
        print(f"ERROR: {cdn_dir} not found", file=sys.stderr)
        sys.exit(1)

    print("=== FORCE-ALL DEPLOY (boto3 only, no remote reads) ===\n", flush=True)

    # Step 0: Regenerate pre-parsed rkyv blobs (fail-loud, same contract as
    # the incremental path — a force deploy with stale blobs would publish a
    # manifest that poisons every rkyv client).
    print("Step 0: Regenerating rkyv blobs...", flush=True)
    regenerate_rkyv_blobs(project_root)
    assert_rkyv_blobs_fresh(cdn_dir)
    print("  rkyv blobs fresh", flush=True)

    # Step 1: Generate + upload manifest
    print("Step 1: Manifest...", flush=True)
    manifest = generate_manifest(cdn_dir)
    manifest_path = cdn_dir / "manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    cc = _cdn_cache.cache_control_for("manifest.json")
    _cdn_s3.upload_file(manifest_path, "manifest.json", cc, dry_run)
    print(f"  manifest.json uploaded ({len(manifest['files'])} files)", flush=True)

    # Step 2: Upload versioned files
    print(f"\nStep 2: Versioned files ({len(VERSIONED_FILES)})...", flush=True)
    for relative_path in VERSIONED_FILES:
        local_path = cdn_dir / relative_path
        if not local_path.is_file():
            print(f"  SKIP {relative_path} (not found)", flush=True)
            continue
        cache_control = _cdn_cache.cache_control_for(relative_path)
        _cdn_s3.upload_file(local_path, relative_path, cache_control, dry_run)
    print(f"  {len(VERSIONED_FILES)} versioned files done", flush=True)

    # Step 3: Sync directories (no remote listing — upload everything)
    print("\nStep 3: Sync directories...", flush=True)
    for dir_name in SYNC_DIRS:
        local_dir = cdn_dir / dir_name
        if not local_dir.is_dir():
            print(f"  {dir_name}/ — not found locally, skipping", flush=True)
            continue

        cache_control = _cdn_cache.cache_control_for(dir_name + "/")
        all_files = [
            p for p in sorted(local_dir.rglob("*"))
            if p.is_file() and p.name != "README.md"
        ]
        total = len(all_files)
        if total == 0:
            print(f"  {dir_name}/ — empty", flush=True)
            continue

        start = _time.time()
        base_prefix = dir_name.rstrip("/") + "/"
        print(f"  {dir_name}/ [{total} files, {cache_control}]", flush=True)

        for i, local_path in enumerate(all_files, 1):
            key = base_prefix + local_path.relative_to(local_dir).as_posix()
            _cdn_s3.upload_file(local_path, key, cache_control, dry_run)

            if i % 200 == 0 or i == total:
                elapsed = _time.time() - start
                rate = i / elapsed if elapsed > 0 else 0
                pct = i * 100 // total
                print(
                    f"    [{i}/{total}] {pct}%  up={i}  "
                    f"{rate:.0f} files/s  {elapsed:.0f}s",
                    flush=True,
                )

    print("\nForce-all deploy complete!", flush=True)


def main() -> None:
    parser = argparse.ArgumentParser(description="Deploy CDN to S3")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be deployed without actually uploading",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Force upload all versioned files, ignoring manifest comparison. "
        "Use when CDN actual files are stale but the manifest is current.",
    )
    parser.add_argument(
        "--force-all",
        action="store_true",
        help="Upload EVERYTHING from cdn/ to R2 via boto3 only. Skips all "
        "remote reads (aws CLI). Use for initial deploy or when aws CLI is "
        "broken. Shows progress bar per directory.",
    )
    parser.add_argument(
        "--verify-remote",
        action="store_true",
        help="Download remote files and verify actual hash matches manifest. "
        "Use to diagnose CDN/S3 inconsistencies. Read-only, never uploads.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Also list unchanged files in the comparison step (default: quiet)",
    )
    parser.add_argument(
        "--ignore-mtime",
        action="store_true",
        help="Directory sync trusts matching byte sizes and skips the mtime "
        "check. Use on machines that are not the deploy origin: a cdn/ "
        "checkout copied after the last deploy has fresh mtimes everywhere, "
        "and the mtime rule would re-upload the whole static tree.",
    )
    args = parser.parse_args()
    dry_run = args.dry_run

    # --force-all: bypass all remote reads, upload everything from cdn/ via boto3
    if args.force_all:
        _force_all_deploy(dry_run)
        return

    if args.verify_remote:
        conflicting = [
            name
            for name, enabled in (
                ("--force", args.force),
                ("--dry-run", args.dry_run),
                ("--verbose", args.verbose),
            )
            if enabled
        ]
        if conflicting:
            print(
                "WARNING: --verify-remote is read-only and ignores "
                f"{', '.join(conflicting)}",
                file=sys.stderr,
            )
        cdn_base_url = _cdn_verify.get_cdn_base_url()
        if not cdn_base_url:
            print(
                "ERROR: ORIGA_CDN_BASE_URL is not set; cannot verify remote",
                file=sys.stderr,
            )
            sys.exit(1)
        problems = _cdn_verify.verify_remote(cdn_base_url)
        if problems != 0:
            sys.exit(1)
        return

    if dry_run:
        print("=== DRY RUN ===\n")

    project_root = Path(__file__).resolve().parent.parent
    cdn_dir = project_root / "cdn"

    if not cdn_dir.is_dir():
        print(f"ERROR: {cdn_dir} not found", file=sys.stderr)
        sys.exit(1)

    # Step 0: Generate bundles (BEFORE manifest so hashes are included)
    print("Step 0: Generating bundles...")
    for script in ["bundle_phrases_data.py", "bundle_kanji_svgs.py"]:
        script_path = Path(__file__).resolve().parent / script
        if script_path.is_file():
            result = subprocess.run(
                [sys.executable, str(script_path)],
                capture_output=True, text=True, cwd=str(script_path.parent),
                check=False,
            )
            if result.returncode != 0:
                print(f"  {script} FAILED: {result.stderr}", file=sys.stderr)
                sys.exit(1)
            for line in result.stdout.strip().splitlines():
                print(f"  {line}")
        else:
            print(f"  {script} not found, skipping")

    # Step 0.5: Regenerate pre-parsed rkyv blobs and verify freshness
    # (BEFORE manifest: blob hashes must be computed from current bytes)
    print("Step 0.5: Regenerating rkyv blobs...")
    regenerate_rkyv_blobs(project_root)
    regenerate_precompute_blobs(project_root)
    assert_rkyv_blobs_fresh(cdn_dir)
    print("  rkyv blobs fresh")

    # Step 1: Generate local manifest
    print("Step 1: Generating local manifest...")
    manifest = generate_manifest(cdn_dir)
    manifest_path = cdn_dir / "manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    file_count = len(manifest["files"])
    print(f"  {file_count} files hashed -> cdn/manifest.json")

    # Step 2: Download remote manifest
    print("\nStep 2: Fetching remote manifest...")
    remote_manifest = _cdn_s3.download_remote_manifest(dry_run)

    # Step 3: Compare
    print("\nStep 3: Comparing manifests...")
    if args.force:
        print("  Force mode: uploading all versioned files")
    changed, unchanged = compute_files_to_upload(manifest, remote_manifest, args.force)
    print(f"  {len(changed)} changed, {len(unchanged)} unchanged")
    for path in sorted(changed):
        print(f"    + {path}")
    if args.verbose:
        for path in sorted(unchanged):
            print(f"    = {path}")

    # Step 3.5: Validate grammar corpus if this deploy ships it
    validate_grammar_if_changed(changed)

    # Step 4: Upload changed versioned files
    print("\nStep 4: Uploading changed versioned files...")
    upload_versioned_files(cdn_dir, changed, dry_run)

    # Step 5: Sync directories
    print("\nStep 5: Syncing directories...")
    sync_directories(cdn_dir, dry_run, args.ignore_mtime)

    # Step 6: Upload manifest
    print("\nStep 6: Uploading manifest...")
    upload_manifest(cdn_dir, dry_run)

    print("\nDone!")


if __name__ == "__main__":
    main()
